### ISSUE TITLE
Breakpoints fail to bind in Node 16 or Chrome 90 in functions with destructured arguments

### ISSUE THREAD

**Issue by richardsimko** [microsoft/vscode-js-debug#1017]
**Describe the bug**
If a file contains two nested anonymous functions with parameters in Node 16 it's impossible to set a breakpoint on the inner function. Minimal example here: richardsimko/vscode-debugger-issues

if you run the code with `npm run start` and try to use any of the debug targets to attach to the process it becomes impossible to set a breakpoint on line 5 of `index.js`.

**To Reproduce**
1. `git clone git@github.com:richardsimko/vscode-debugger-issues.git`
2. `npm run start`
3. Launch debug target
4. Try to set breakpoint in the inner function

**Log File**

I've attached a log file of me launching the debug config, trying to add the breakpoint and quitting the debug config.

**VS Code Version:** 1.56.2

**Additional context**
Possibly related to using `type: module`, but I'm not sure. It works on any node versions <16 and I couldn't find anything specific to neither the debugger nor ESM in the patch notes.

**Comment by connor4312** [comment]
This looks like a bug in V8 that was fixed in Chrome 91. It's pretty bad, it seems that they fail to bind breakpoints in any function that has destructured arguments.

It should be fixed in Node.js once they pick up the latest V8 build.

**Comment by connor4312** [comment]
I'll add a warning if we detect usages of Node 16-16.2

**Comment by richardsimko** [comment]
Thanks for the reply! I'll hold out for a Node update.

**Comment by richardsimko** [comment]
@connor4312 I saw that you added the warning for 16.2 but the issue is still present in 16.3.

**Comment by connor4312** [comment]
Please verify the warning is present; 16.3 was just released on Thursday and I don't plan to push candidate fixes for this (or future) releases. It's a helpful hint to exist, but Node will continue releasing updates and I will patch for them on our normal release cadence.

**Comment by JacksonKearl** [comment]
Did not see any notification when running the above repro steps. 
![recording (23)](https://user-images.githubusercontent.com/8586769/120873189-e92f1100-c555-11eb-9f88-b22b7bf5fc3f.gif)

**Comment by connor4312** [comment]
@JacksonKearl it's only shown when launching Node. When attaching we don't get the version in the same way.

**Comment by JacksonKearl** [comment]
Tried these launch configs and never saw a notification?
```
{
    "configurations": [
        {
            "command": "npm start",
            "name": "Run npm start",
            "request": "launch",
            "type": "node-terminal"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/index.js",
            "skipFiles": [
                "<node_internals>/**"
            ]
        },
        {
            "name": "Launch via NPM",
            "request": "launch",
            "runtimeArgs": [
                "run-script",
                "start"
            ],
            "runtimeExecutable": "npm",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "pwa-node"
        },
        {
            "name": "Attach",
            "port": 9393,
            "request": "attach",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "pwa-node"
        },
    {
        "name": "Attach: process",
        "processId": "${command:PickProcess}",
        "request": "attach",
        "skipFiles": [
            "<node_internals>/**"
        ],
        "type": "pwa-node",
        "restart": true,
    }
    ]
}
```

**Comment by connor4312** [comment]
Hm, those should work. Can you stick a trace: true in `Launch Program` and share the logs?

**Comment by JacksonKearl** [comment]
Ah, I see it. I was expecting a pop-up. 
![image](https://user-images.githubusercontent.com/8586769/120875060-94dc5f00-c55e-11eb-942d-2f497ae6e053.png)

**Comment by connor4312** [comment]
Yea, I figured a popup might be too intrusive. If breakpoints aren't working, I think most users' first inclination will be to check the console for errors, so I figured it was a decent place for it.

**Comment by JacksonKearl** [comment]
Fair enough. Though I cant shake that it might be nicer to assume Node.js 16.X broken until confirmed fixed versus constantly having folks who install the latest release be confused until we get to bumping our known-broken limit.

**Comment by icetbr** [comment]
I think this is the MR we're waiting for.
https://github.com/nodejs/node/pull/38273

**Comment by ppicom** [comment]
What options do those of us that are running Mac with M1 chips and hence cannot downgrade to node 14 have? :D wait for the fix? Is there a workaround? Thanks!

**Comment by richardsimko** [comment]
It works in Node 15 if that runs on M1. Otherwise I saw that the PR to upgrade V8 has been merged so I would presume it will be released in the next minor for 16.

**Comment by ppicom** [comment]
I can't seem to run v15 on mac M1. On every post I find online they say is as simple as `nvm install v15` but in my case that yields a cascade of error logs. Will ask for some help on node's repo :D thanks @richardsimko for your answer!
