### ISSUE TITLE
`perScriptSourceMaps: auto` does not kick in for vite dev server

### ISSUE THREAD

**Issue by JosefSaltz** [microsoft/vscode-js-debug#1739]
**Describe the bug**
I am having no luck getting VScode to debug correctly in my React project when using Vite as my dev server. Breakpoints either fail to bind or hoist immediately to the top function declaration in the file. Browsers hang and crash when I refresh with a break point set. I previously was using Create React App's react-scripts before it was deprecated.

**To Reproduce**
1. Set up a generic Chrome launch debug config (attached mine below)
2. Install Vite latest major to a boilerplate react project.
3. Launch the debug profile after starting the Vite dev server
4. Set a breakpoint in VScode
5. Refresh page
6. Page either hangs or loads a transpiled file in VScode Editor

**Log File**

**VS Code Version:** 1.79.2

**Additional context**

I am running my project in WSL2 remote but I also saw the same problems on my laptop running Fedora 38.

Here's my launch.json
```json
{

  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Chrome",
      "request": "launch",
      "type": "chrome",
      "url": "http://127.0.0.1:3000",
      "trace": true,
      "webRoot": "${workspaceFolder}"
    }
  ]
}
```

**Comment by connor4312** [comment]
I'm not able to reproduce this using the template from `npm create vite@latest -- --template react`. Can you please share your log file using the instructions in the issue template?

**Comment by JosefSaltz** [comment]
Sorry about, that I missed the path in the debug console, here's two logs I have from that day.

[vscode-debugadapter-aabad219.json.gz](https://github.com/microsoft/vscode-js-debug/files/11889459/vscode-debugadapter-aabad219.json.gz)
[vscode-debugadapter-a07d1dd9.json.gz](https://github.com/microsoft/vscode-js-debug/files/11889460/vscode-debugadapter-a07d1dd9.json.gz)

**Comment by connor4312** [comment]
I think in your case setting `"perScriptSourcemaps": "yes"` in your launch config should resolve the issue. It seems for some reason the default `auto` setting is not detecting Vite's style of sourcemaps, we should improve that.

**Comment by JosefSaltz** [comment]
I will give that a try however, I'm getting this lint error 

![image](https://github.com/microsoft/vscode-js-debug/assets/11865958/ab209eb8-2bf0-42cb-bf5c-71af5a26d080)

**Comment by connor4312** [comment]
The property is case sensitive, it's `perScriptSourcemaps` not `perScriptSourceMaps`

**Comment by JosefSaltz** [comment]
Thanks for catching that. 😅

The linter is no longer freaking out about that key. However, I'm still seeing breakpoints being set in a remote transpiled version of the file rather than the actual source file.

![image](https://github.com/microsoft/vscode-js-debug/assets/11865958/f1eb57eb-5d85-4dfd-8acc-c32cdae73d8b)

**Comment by JosefSaltz** [comment]
Could we perhaps re-title this issue? I feel like the current title does not actually capture the problem at hand.

**Comment by connor4312** [comment]
Regarding your last comment, that is likely a sourcemap generation issue on Vite's side. As the debugger diagnostics indicate, we follow the sourcemap and set breakpoint at those compiled locations, but they either don't bind or bind to the wrong location. If the debugger then pauses at that wrong location, or any location where there's not an available sourcemapping, we show the compiled file.

**Comment by JosefSaltz** [comment]
Hello, we're now at Vite 4.5, I still cannot get breakpoints to bind. This is a major productivity hindrance at my job and I can't rationalize why two extremely popular tools are not playing well. Is there any further logs or traces I can provide?

**Comment by connor4312** [comment]
The remaining issue you spoke about earlier is on Vite's side. The JS debugger follows the sourcemaps; if the sourcemaps are unreliable, it has nothing to go on.

**Comment by JosefSaltz** [comment]
> The remaining issue you spoke about earlier is on Vite's side. The JS debugger follows the sourcemaps; if the sourcemaps are unreliable, it has nothing to go on.

Understood, I've followed up and opened a issue in their repository.
