### ISSUE TITLE
[Debug: Create JavaScript Debug Terminal] Executing the script does not trigger debugging

### ISSUE THREAD

**Issue by finite-light** [microsoft/vscode-js-debug#488]
* VS Code Version: 1.43.2
* JavaScript Debugger (Nightly) Version: 2020.5.2617

Steps to reproduce:
  1. Create a one-off terminal for debugging via the Debug: Create JavaScript Debug Terminal command
  2. Execute the script command on the terminal created in the previous step, but the debugging process is not triggered

I added the following configuration into the `settings.json`:
```json
{
  "debug.javascript.usePreview": true,
  "debug.javascript.debugByLinkOptions": "always",
}
```

![image](https://user-images.githubusercontent.com/62316053/82994217-61eeb980-a034-11ea-9f03-8c89ec00178c.png)

**Comment by connor4312** [comment]
Thanks -- to confirm what I think the issue is, what's the value of your `debug.node.autoAttach` setting?

**Comment by connor4312** [comment]
Fixed this incompatibility. When updating to the latest nightly, you will want to disable and then re-enable auto attach to get the fix.

**Comment by finite-light** [comment]
Thank you for replying so quickly. 
My previous `debug.node.autoAttach` setting is `disabled`. I tried to follow your suggestion to reinstall the `JavaScript Debugger (Nightly)` extension and enable the `debug.node.autoAttach` , but it still doesn't seem to work.

**Comment by connor4312** [comment]
huh, interesting. If you just run `node` in the terminal, does the debugger attach then?

**Comment by finite-light** [comment]
No, still doesn't work. 
![image](https://user-images.githubusercontent.com/62316053/83114275-5a461800-a0fb-11ea-8d1f-7a8f7608c395.png)

By the way, I am using ssh-remote extension and the remote server is a ubuntu18.04-x64  virtual machine running in vmware. About a month ago, `JavaScript Debugger (Nightly)` works for me, but recently I tried to reinstall the version at that time, but it still does not work.

And, this extension is still works in my local machine.
![image](https://user-images.githubusercontent.com/62316053/83114680-de000480-a0fb-11ea-88dd-de71a157c60c.png)

**Comment by connor4312** [comment]
I'm having trouble reproducing this on my systems. On the _latest_ nightly, please let me know what the following outputs for you: `echo $NODE_OPTIONS && echo $VSCODE_INSPECTOR_OPTIONS`

If those aren't present it's possible we or vscode is failing to set the environment variables. I don't recognize the prompt in your terminal -- what shell are you using?

**Comment by finite-light** [comment]
This issue happened on my work computer at the company, I will confirm and reply to you as soon as possible next Monday.

I am using  bash (in a remote ubuntu18.04-x64 virtual machine in the vmware connected via the `VSCode Remote - SSH (ms-vscode-remote.remote-ssh)` extension).

**Comment by finite-light** [comment]
> I'm having trouble reproducing this on my systems. On the _latest_ nightly, please let me know what the following outputs for you: `echo $NODE_OPTIONS && echo $VSCODE_INSPECTOR_OPTIONS`

I got this.
![image](https://user-images.githubusercontent.com/62316053/83367297-6de8cb80-a3e6-11ea-8595-0468be55a4b5.png)

It does seem that vscode failed to set the environment variables. Can I set them manually? What should I do?

**Comment by finite-light** [comment]
Well, by comparing the locally valid variables, I manually added the variable `export NODE_OPTIONS='--require "/home/virtual/.vscode-server/extensions/ms-vscode.js-debug-nightly-2020.5.2917/src/bootloader.bundle.js"'` in the terminal created by `Debug: Create JavaScript Debug Terminal`, and now it takes effect.

But why? And is there any way for me to make this variable effective every time only in the terminal created by `Debug: Create JavaScript Debug Terminal`?

**Comment by connor4312** [comment]
It looks like the variables we're setting in the terminal aren't taking effect. cc @Tyriar

**Comment by Tyriar** [comment]
@finite-light can you do a trace log as described here to see what the environment is getting set to? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

Note if you have any sensitive values in the environment you'll want to remove them before posting to GH.

**Comment by finite-light** [comment]
@Tyriar I'm afraid not. The second step in the link you gave needs to close all vscode, but the problem I encountered is under the remote machine, so usually I need to start vscode locally and then open the remote working directory via the `Remote-SSH` extension. I don’t know how to directly start the vscode connected to the remote server through the `code` command, how can I do this?

**Comment by Tyriar** [comment]
@finite-light you can also enable this with a command at runtime as well:

![image](https://user-images.githubusercontent.com/2193314/83764032-46843f80-a62e-11ea-84b6-0ae3422b57e0.png)

I should probably include that in the instructions, the reason it says to close all windows is because that's one of the first steps in diagnosing terminal issues (as the environment is pulled from a potentially stale environment).

**Comment by finite-light** [comment]
@Tyriar Yes, I saw your supplement, which is more friendly than before，thank you!

This is my [trace.log](https://github.com/microsoft/vscode-js-debug/files/4733339/trace.log), is it what you exactly want? I deleted a lot of log contents starting with `[trace] [storage state.vscdb]` and use `<..omit..>` as a placeholder for my deleted part, they all seem to be some data related to the editor state and the working directory (I am also curious why it outputs so many contents so many times), hope this will not affect for you to locate the problem.

**Comment by Tyriar** [comment]
It looks like the variables are getting set:

```
[2020-06-05 08:42:39.789] [renderer3] [trace] terminalInstance#ctor (id: 7) {"name":"JavaScript Debug Terminal","cwd":"/home/virtual/temp/redux-demo","ignoreConfigurationCwd":true,"env":{"NODE_OPTIONS":"--require \"/home/virtual/.vscode-server/extensions/ms-vscode.js-debug-nightly-2020.6.417/src/bootloader.bundle.js\" ","VSCODE_INSPECTOR_OPTIONS":"{\"inspectorIpc\":\"/tmp/node-cdp.2694-2.sock\",\"deferredMode\":false,\"waitForDebugger\":\"\",\"execPath\":\"/usr/me/node/bin/node\",\"onlyEntrypoint\":false,\"fileCallback\":\"/tmp/node-debug-callback-a6ac42e397407d5c\"}"}}
```

You might have something in your start up scripts which is clearing out the variables?

**Comment by finite-light** [comment]
Yes, you are right, I found this environment variable declaration in `~/.bashrc`:
  
  ```shell
  export NODE_OPTIONS=--max_old_space_size=4096
  ```

This may be the solution I found to alleviate the memory consumption problem of Node.js (I can't remember the details), can I let it continue to work?

**Comment by finite-light** [comment]
I forgot that the shell variables can be concatenated, and now it works correctly:
```shell
export NODE_OPTIONS="--max_old_space_size=4096 ${NODE_OPTIONS}"
```

Thank your for the help! I'm sorry I didn't check my shell variable configuration when I knew `NODE_OPTIONS` was a key environment variable.
