### ISSUE TITLE
Breakpoints appear to be on wrong lines

### ISSUE THREAD

**Issue by cnshenj** [microsoft/vscode-js-debug#524]
I see the fix for issue #407 is included in VSCode 1.46.0. But I'm still hitting the issue when debugging a Jest test. If I change `debug.javascript.usePreview` to `false`, the breakpoints are properly marked.

### Repro steps
1. Install VSCode 1.46.x
2. Set `debug.javascript.usePreview` to `true`
3. Clone [managed-cache](https://github.com/cnshenj/managed-cache) then run `npm install`
4. Open the project in VSCode and set a breakpoint at the first test (line 35 in test.ts)
5. Start a debug session
6. **When the first breakpoint is hit**, try to set a new breakpoint in `getCacheItem` method (line 31-44 in cache-manager.ts)

### Expected
Breakpoint set on the desired line.

### Actual
Breakpoint appears to be on a different line.

**Comment by connor4312** [comment]
Thanks for the good issue! One more edge case with overlaid source maps, fixed in today's nightly build

**Comment by JacksonKearl** [comment]
Seems to be working now, though I wasn't able to repo in 1.46

**Comment by connor4312** [comment]
If your 1.46 install has a nightly or recent stable version of js-debug, it will have gotten the fix already 🙂

**Comment by JacksonKearl** [comment]
I had nightly at first and I thought that was it, but now I'm on 1.46.1 and still not reproing
