### ISSUE TITLE
"No data available yet" after a second

### ISSUE THREAD

**Issue by BrightSoul** [microsoft/vscode-js-debug#798]
Hello everyone, first of all thanks for such a useful extension. It's working nicely on a simple JavaScript project I made.
In a more complex project, however, it stops working after a second and it displays "No data available yet". See this image.

![flame](https://user-images.githubusercontent.com/1888641/95559647-6383b180-0a18-11eb-9935-684a0f186d77.gif)

After this happens, I try to run the "Debug: Toggle Visible Performance Charts" but none of the metrics (CPU, Heap, ...) are shown any longer. Again, see the image.

![metrics](https://user-images.githubusercontent.com/1888641/95560293-5dda9b80-0a19-11eb-8562-cad69230bfe5.gif)

How can I known what the problem is? This extension doesn't seem to have its own output channel. The Log (Extension host) panel is not showing anything meaningful either.

I'm using VSCode 1.50.0 (user install) on Windows 10 and this is my launch.json file.

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Debug Chrome",
            "url": "http://localhost:3000",
            "port": 9222,
            "webRoot": "${workspaceRoot}/v2/src",
            "sourceMaps": true,
            "disableNetworkCache": true,
            "breakOnLoad": false,
            "skipFiles": [
                "${workspaceFolder}/node_modules/**/*.js",
                "<node_internals>/**/*.js"
            ],
            "preLaunchTask": "serve",
            "smartStep": true
        }
    ]
}
```

**Comment by connor4312** [comment]
You'll need to use the [nightly debugger build](https://github.com/microsoft/vscode-js-debug#nightly-extension) to get the fix.

**Comment by rzhao271** [comment]
Hi @brightsoul, I'm wondering whether this issue is now resolved for you?

**Comment by connor4312** [comment]
To verify this:

1. Have a webpage that has a webworker or service worker (e.g. https://github.com/microsoft/vscode-js-debug/tree/master/demos/web-worker)
1. Select the webworker or service worker in the call stack view
1. Verify (with the flame graph extension installed) that the realtime performance graphs still show

**Comment by BrightSoul** [comment]
Hello @rzhao271 and @connor4312, yes the issue is resolved for me, thanks.
